name: Deploy from Netbird network

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Install NetBird
      #   run: |
      #     curl -fsSL https://pkgs.netbird.io/install.sh | sudo bash

      - name: Netbird Connect
        uses: Alemiz112/netbird-connect@v1
        with:
          setup-key: ${{ secrets.NETBIRD_SETUP_KEY }}
          management-url: 'https://https://app.netbird.io'

      - name: Wait for Netbird Route
        run: |
          echo "Waiting for Netbird routes to stabilize..."
          sleep 15
          sudo netbird status
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Deploy (git pull)
        run: |
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i ~/.ssh/id_rsa akmmp@100.76.254.197 '
            set -e
            cd ${{ secrets.SERVER_PATH }}
            git pull origin main
          '
