name: Deploy from Netbird network

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install NetBird
        run: |
          curl -fsSL https://pkgs.netbird.io/install.sh | sudo bash

      # - name: Connect to NetBird
      #   run: |
      #     sudo netbird up --setup-key ${{ secrets.NETBIRD_SETUP_KEY }}
      #     for i in {1..10}; do
      #       if sudo netbird status | grep -q "Connected"; then
      #         echo "NetBird connected successfully"
      #         break
      #       fi
      #       echo "Waiting for NetBird..."
      #       sleep 5
      #     done
      
      name: Netbird Connect
        id: netbird
        uses: Alemiz112/netbird-connect@v1.0.1
        with:
          setup-key: ${{ secrets.NETBIRD_SETUP_KEY }}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Deploy (git pull)
        run: |
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -i ~/.ssh/id_rsa akmmp@100.76.254.197 '
            set -e
            cd ${{ secrets.SERVER_PATH }}
            git pull origin main
          '
